export const languages = {
  "en-US": "English (US)",
  // "en-GB": "English (UK)",
  // "en-IN": "English (India)",
  // "en-AU": "English (Australia)",
  // "en-CA": "English (Canada)",
  // "en-AE": "English (UAE)",
  // "en-SG": "English (Singapore)",
  // "hi-IN": "Hindi",
  // "te-IN": "Telugu",
  // "ta-IN": "Tamil",
  // "kn-IN": "Kannada",
  // "ml-IN": "Malayalam",
  // "mr-IN": "Marathi",
  // "bn-IN": "Bengali",
  // "gu-IN": "Gujarati",
  // "pa-IN": "Punjabi",
  // "ur-IN": "Urdu",
  // "or-IN": "Odia",
  // "as-IN": "Assamese",
  // "ne-IN": "Nepali",
  // "sa-IN": "Sanskrit",
  // "kok-IN": "Konkani",
  // "mai-IN": "Maithili",
  // "sd-IN": "Sindhi",
  // "doi-IN": "Dogri",
  // "mni-IN": "Manipuri",
  // "ks-IN": "Kashmiri",
  // "sat-IN": "Santali",
  // "ar-AE": "Arabic (UAE)",
  // "ar-SA": "Arabic (Saudi Arabia)",
  // "ar-QA": "Arabic (Qatar)",
  // "ar-KW": "Arabic (Kuwait)",
  // "ar-BH": "Arabic (Bahrain)",
  // "ar-OM": "Arabic (Oman)",
  // "ar-EG": "Arabic (Egypt)",
  // "fa-IR": "Persian (Iran)",
  // "ur-PK": "Urdu (Pakistan)",
  // "tr-TR": "Turkish",
  // "fr-FR": "French (France)",
  // "fr-CA": "French (Canada)",
  // "de-DE": "German",
  // "es-ES": "Spanish (Spain)",
  // "es-MX": "Spanish (Mexico)",
  // "it-IT": "Italian",
  // "pt-PT": "Portuguese (Portugal)",
  // "pt-BR": "Portuguese (Brazil)",
  // "nl-NL": "Dutch",
  // "ru-RU": "Russian",
  // "uk-UA": "Ukrainian",
  // "pl-PL": "Polish",
  // "sv-SE": "Swedish",
  // "da-DK": "Danish",
  // "no-NO": "Norwegian",
  // "fi-FI": "Finnish",
  // "el-GR": "Greek",
  // "cs-CZ": "Czech",
  // "ro-RO": "Romanian",
  // "hu-HU": "Hungarian",
  // "zh-CN": "Chinese (Simplified)",
  // "zh-TW": "Chinese (Traditional)",
  // "ja-JP": "Japanese",
  // "ko-KR": "Korean",
  // "th-TH": "Thai",
  // "vi-VN": "Vietnamese",
  // "id-ID": "Indonesian",
  // "ms-MY": "Malay",
  // "fil-PH": "Filipino",
  // "he-IL": "Hebrew",
  // "sw-KE": "Swahili",
  // "af-ZA": "Afrikaans",
} as const;

export type LanguageCode = keyof typeof languages;